#!/bin/bash

set -m

# Only run this script once
s6-svc -O /var/run/s6/services/tailscale

echo "Starting tailscaled"
/app/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/var/run/tailscale/tailscaled.sock &

echo -n "Sleeping for 5 seconds for tailscaled to finish ... "
sleep 5
echo "done"

echo "Starting tailscale"
until /app/tailscale up \
    --authkey="${TAILSCALE_AUTH_KEY}" \
    --hostname="fli-hole${FLY_REGION}" \
    --advertise-exit-node
do
    sleep 0.1
done
